[package]
name = "rt-navi"
version = "0.0.1"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "High precision navigation in real time"
homepage = "https://github.com/rtk-rs/rt-navi"
repository = "https://github.com/rtk-rs/rt-navi"
keywords = ["navigation", "gps", "glonass", "galileo", "timing"]
categories = [
    "science",
    "science::geo",
    "command-line-interface",
    "command-line-utilities",
]
edition = "2021"
readme = "README.md"

[dependencies]
log = "0.4"
thiserror = "2"
env_logger = "0.11.8"
chrono = "0.4.29"

serialport = "4.7"
ublox = { git = "https://github.com/ublox-rs/ublox", branch = "master" }

rtcm-rs = "0.11"

tokio = { version = "1.45.0", features = ["full"] }
clap = { version = "4.5", features = ["derive", "color"] }

hifitime = { version = "4.0", features = ["serde", "std"] }
anise = { git = "https://github.com/nyx-space/anise", branch = "dep/hifitime-github", features = ["embed_ephem"] }

gnss-rs = { version = "2.3.5", features = ["serde"] }
gnss-rtk = { path = "../gnss-rtk", features = ["serde"] }
# gnss-rtk = { git = "https://github.com/rtk-rs/gnss-rtk", branch = "main", features = ["serde"] }

# gpx = { version = "0.10", optional = true }
# kml = { version = "0.8", optional = true }
