name: rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
    
    - name: Dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - uses: actions-rs/cargo@v1
      name: Linter 
      with:
        command: fmt
        args: --all -- --check
    
    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with:
        command: build
        args: --all-features --release
    
    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test
        args: --all-features --verbose
    
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
        
    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with: 
        command: build 
        args: --all-features --release
  
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
    
    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with: 
        command: build 
        args: --all-features --release
